
// -*- C++ -*-
// $Id$
// Definition for Win32 Export directives.
// This file is generated automatically by generate_export_file.pl knCoordinatedWheelLocomotion
// ------------------------------
#ifndef KNCOORDINATEDWHEELLOCOMOTION_EXPORT_H
#define KNCOORDINATEDWHEELLOCOMOTION_EXPORT_H

#include "ace/config-all.h"

#if defined (ACE_AS_STATIC_LIBS) && !defined (KNCOORDINATEDWHEELLOCOMOTION_HAS_DLL)
#  define KNCOORDINATEDWHEELLOCOMOTION_HAS_DLL 0
#endif /* ACE_AS_STATIC_LIBS && KNCOORDINATEDWHEELLOCOMOTION_HAS_DLL */

#if !defined (KNCOORDINATEDWHEELLOCOMOTION_HAS_DLL)
#  define KNCOORDINATEDWHEELLOCOMOTION_HAS_DLL 1
#endif /* ! KNCOORDINATEDWHEELLOCOMOTION_HAS_DLL */

#if defined (KNCOORDINATEDWHEELLOCOMOTION_HAS_DLL) && (KNCOORDINATEDWHEELLOCOMOTION_HAS_DLL == 1)
#  if defined (KNCOORDINATEDWHEELLOCOMOTION_BUILD_DLL)
#    define knCoordinatedWheelLocomotion_Export ACE_Proper_Export_Flag
#    define KNCOORDINATEDWHEELLOCOMOTION_SINGLETON_DECLARATION(T) ACE_EXPORT_SINGLETON_DECLARATION (T)
#    define KNCOORDINATEDWHEELLOCOMOTION_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_EXPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  else /* KNCOORDINATEDWHEELLOCOMOTION_BUILD_DLL */
#    define knCoordinatedWheelLocomotion_Export ACE_Proper_Import_Flag
#    define KNCOORDINATEDWHEELLOCOMOTION_SINGLETON_DECLARATION(T) ACE_IMPORT_SINGLETON_DECLARATION (T)
#    define KNCOORDINATEDWHEELLOCOMOTION_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK) ACE_IMPORT_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#  endif /* KNCOORDINATEDWHEELLOCOMOTION_BUILD_DLL */
#else /* KNCOORDINATEDWHEELLOCOMOTION_HAS_DLL == 1 */
#  define knCoordinatedWheelLocomotion_Export
#  define KNCOORDINATEDWHEELLOCOMOTION_SINGLETON_DECLARATION(T)
#  define KNCOORDINATEDWHEELLOCOMOTION_SINGLETON_DECLARE(SINGLETON_TYPE, CLASS, LOCK)
#endif /* KNCOORDINATEDWHEELLOCOMOTION_HAS_DLL == 1 */

// Set KNCOORDINATEDWHEELLOCOMOTION_NTRACE = 0 to turn on library specific tracing even if
// tracing is turned off for ACE.
#if !defined (KNCOORDINATEDWHEELLOCOMOTION_NTRACE)
#  if (ACE_NTRACE == 1)
#    define KNCOORDINATEDWHEELLOCOMOTION_NTRACE 1
#  else /* (ACE_NTRACE == 1) */
#    define KNCOORDINATEDWHEELLOCOMOTION_NTRACE 0
#  endif /* (ACE_NTRACE == 1) */
#endif /* !KNCOORDINATEDWHEELLOCOMOTION_NTRACE */

#if (KNCOORDINATEDWHEELLOCOMOTION_NTRACE == 1)
#  define KNCOORDINATEDWHEELLOCOMOTION_TRACE(X)
#else /* (KNCOORDINATEDWHEELLOCOMOTION_NTRACE == 1) */
#  if !defined (ACE_HAS_TRACE)
#    define ACE_HAS_TRACE
#  endif /* ACE_HAS_TRACE */
#  define KNCOORDINATEDWHEELLOCOMOTION_TRACE(X) ACE_TRACE_IMPL(X)
#  include "ace/Trace.h"
#endif /* (KNCOORDINATEDWHEELLOCOMOTION_NTRACE == 1) */

#endif /* KNCOORDINATEDWHEELLOCOMOTION_EXPORT_H */

// End of auto generated file.
